# Generated by Django 4.0.5 on 2022-06-29 11:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='', max_length=10)),
                ('dob', models.DateField()),
                ('application_letter', models.ImageField(default='/letters/default.jpg', upload_to='letters')),
                ('areas_of_interest', models.TextField()),
                ('university', models.CharField(default='', max_length=100)),
                ('date_application', models.DateTimeField(default=datetime.datetime(2022, 6, 29, 11, 53, 36, 120346, tzinfo=utc))),
                ('qualified', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
