# Generated by Django 4.0.5 on 2022-06-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_alter_internshipapplications_date_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='/gallery/default.jpg', upload_to='gallery')),
                ('figcaption', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
